// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIvroGT_bm6osgwI2e0kXJiM4std6RAfk',
    appId: '1:976774407007:web:f6cdf41d2f846593398cea',
    messagingSenderId: '976774407007',
    projectId: 'email-sms-auth-example',
    authDomain: 'email-sms-auth-example.firebaseapp.com',
    storageBucket: 'email-sms-auth-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKrAd4FjgdqyQy0Pq50bODWqNCoM7AjM',
    appId: '1:976774407007:android:0af21183533551eb398cea',
    messagingSenderId: '976774407007',
    projectId: 'email-sms-auth-example',
    storageBucket: 'email-sms-auth-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJ2a-wW6s-Low10DhzWnDpVoItmSR3xA',
    appId: '1:976774407007:ios:ad51907eae61922b398cea',
    messagingSenderId: '976774407007',
    projectId: 'email-sms-auth-example',
    storageBucket: 'email-sms-auth-example.appspot.com',
    iosBundleId: 'com.example.emailSmsAuthFirebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARJ2a-wW6s-Low10DhzWnDpVoItmSR3xA',
    appId: '1:976774407007:ios:ad51907eae61922b398cea',
    messagingSenderId: '976774407007',
    projectId: 'email-sms-auth-example',
    storageBucket: 'email-sms-auth-example.appspot.com',
    iosBundleId: 'com.example.emailSmsAuthFirebaseExample',
  );
}
